<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="density" value="2500"/>
  <xacro:macro name="box_inertia" params="lenx leny lenz">
    <xacro:property name="mass" value="${density * lenx * leny * lenz}"/>
    <mass value="${mass}" />
    <inertia 
      ixx="${mass*(lenz*lenz+leny*leny)/12.0}" ixy="0.0" ixz="0.0"
      iyy="${mass*(lenz*lenz+lenx*lenx)/12.0}" iyz="0.0"
      izz="${mass*(lenx*lenx+leny*leny)/12.0}" />
  </xacro:macro>
</robot>
